language: python

python:

  - "3.6"

install:
  -  "pip install -r requirements.txt"
  -  pip install coveralls
  -  pip install coverage
  
 

script:
   pytest Endpoints/ --cov=test_Fast_Food_Fast

after_success:
  coveralls
