language: python


python:

   -'3.4'
  -'3.6'






install:

  - pip install -r requirements.txt
  - pip install coverage


scripts:

<<<<<<< HEAD
  - pytest  test_Fast_Food_Fast.py --cov=test_Fast_Food_Fast

=======
  - pytest test_Fast_Food_Fast.py --cov=test_Fast_Food_Fast
>>>>>>> 19864d579dd070ebee19368a6745bd91125a08d7

after_success: coveralls
