language: python


python:

   -'3.4'
  -'3.6'






install:

  - pip install -r requirements.txt
  - pip install coverage


scripts:

  - pytest  test_Fast_Food_Fast.py --cov=test_Fast_Food_Fast

after_success: coveralls
